# autogenerated by genmsg_py from Finger.msg. Do not edit.
import roslib.message
import struct

## \htmlinclude Finger.msg.html

class Finger(roslib.message.Message):
  _md5sum = 'dfc4b92a1fd0d7b2b47db02338ba9686'
  _type = 'multitouch_nav/Finger'
  _has_header = False #flag to mark the presence of a Header object
  # Pseudo-constants
  FINGER_DOWN = 1
  FINGER_DRAG = 2
  FINGER_UP = 3

  __slots__ = ['id','x','y','eventType']

  ## @param args: fields to set, in .msg order: ['id', 'x', 'y', 'eventType']
  def __init__(self, *args):
    if args:
      assert len(args) == 4
      self.id = args[0]
      self.x = args[1]
      self.y = args[2]
      self.eventType = args[3]
    else:
      self.id = None
      self.x = None
      self.y = None
      self.eventType = None

  def serialize(self, buff):
    buff.write(struct.pack('<b2ib', self.id, self.x, self.y, self.eventType))

  def deserialize(self, str):
    try:
      end = 0
      start = end
      end += 10
      (self.id, self.x, self.y, self.eventType,) = struct.unpack('<b2ib',str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

