#!/usr/bin/python
import subprocess as sub
import sys, os, time

def printr(line):
    red = '\033[0;31m'
    default = '\033[00;00m'
    print red + line + default

def check_for_msg(line):
    if line[:5] == "Got a":
        printr("Dustbuster: " + line[:-1])
        return 1
    else:
        return 0

dirname = sys.argv[1]
filebase = "fg"
snap = "$ROS_PACKAGE_PATH/util/megamaid/bin/dustbuster --seq " + dirname + " " + filebase + " videre/cal_params labeled_images videre/cloud_smallv videre/images"
printr("using cmd: " + snap)
p = sub.Popen("xterm -e $ROS_PACKAGE_PATH/visualization/scene_labeler/bin/image_bg_subtr", shell=True)

while True:
    printr( "Starting scene collection.")
    os.system('ssh -f prc0 "killall gthumb"')
    time.sleep(.3)
    os.system('ssh -f prc0 "DISPLAY=:0.0 gthumb /home/teichman/Desktop/projector-off.png -f"')
    printr("Press enter when you have constructed your mask in image_bg_subtr")
    raw_input("")
    os.system('ssh -f prc0 "killall gthumb"')
    time.sleep(.3)
    os.system('ssh -f prc0 "DISPLAY=:0.0 gthumb ~/Desktop/y3.png -f"')
    time.sleep(2)
                
    snap_p = sub.Popen(snap, shell=True, stdout=sub.PIPE);
    nMsgs = 0;
    while True:
        line = snap_p.stdout.readline()
        nMsgs += check_for_msg(line)
        if(nMsgs == 6):
            break
        
    printr( "All msgs but labeled_images have been recorded.")
    os.system('ssh -f prc0 "killall gthumb"')
    time.sleep(.3)
    os.system('ssh -f prc0 "DISPLAY=:0.0 gthumb /home/teichman/Desktop/projector-off.png -f"')
    printr( "Now send output from image_bg_subtr by pressing 'o' in the segmentation window.")
    snap_p.wait()
    printr( "=== Done collecting that scene. ===")
