#!/usr/bin/python
import subprocess as sub
import sys, os, time

def printr(line):
    red = '\033[0;31m'
    default = '\033[00;00m'
    print red + line + default

def check_for_msg(line):
    if line[:5] == "Got a":
        printr("Dustbuster: " + line[:-1])
        return 1
    else:
        return 0

dirname = sys.argv[1]
filebase = "fg"
snap = "`rospack find megamaid`/bin/dustbuster --seq " + dirname + " " + filebase + " videre/cal_params labeled_images videre/cloud_smallv videre/images"
printr("using cmd: " + snap)
p = sub.Popen("xterm -e `rospack find scene_labeler`/bin/image_bg_subtr_multi", shell=True)

printr( "Set projector blank" )

while True:
    printr( "Starting scene collection.")
    printr("Press enter when you have constructed your mask in image_bg_subtr")
    raw_input("")
    os.system('ssh -f prc0 "killall -s USR1 lpg"')
    time.sleep(1)
                
    snap_p = sub.Popen(snap, shell=True, stdout=sub.PIPE);
    nMsgs = 0;
    while True:
        line = snap_p.stdout.readline()
        nMsgs += check_for_msg(line)
        if(nMsgs == 3):
            break
        
    printr( "All msgs but labeled_images have been recorded.")
    os.system('ssh -f prc0 "killall -s USR1 lpg"')
    printr( "Now send output from image_bg_subtr by pressing 'o' in the segmentation window.")
    snap_p.wait()
    printr( "=== Done collecting that scene. ===")
