/*
 * Copyright (c) 2008, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Willow Garage, Inc. nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * WxRos panel for viewing roserr.
 *
 * Written by Matthew Piccoli
 */
#ifndef __RoserrPanel__
#define __RoserrPanel__

/**
@mainpage

@htmlinclude manifest.html

@b Subclass of the Launcher window

<hr>

@section usage
Run make on the included Makefile.
Ensure that a botherder is running.

@section topic ROS topics

Subscribes to (name/type):
- @b "/roserr"/rostools::Log : Error messages received.  Topic can be changed.

@file
Subclass of RoserrPanelBase, which is generated by wxFormBuilder.
*/

#include "roserrGenerated.h"
#include "ros/node.h"
#include "rostools/Log.h"

/** Implementing RoserrPanelBase */
class RoserrPanel : public RoserrPanelBase
{
protected:
	// Handlers for RoserrPanelBase events.
	///Called when the enable checkbox is clicked, calls SetEnabled
	void OnEnable( wxCommandEvent& );
	///Called when the font is changed and changes the font of the entire panel
	void OnFontChange( wxFontPickerEvent& event );
	///Called when the setup button is clicked and launches the setup window
	void OnSetup( wxCommandEvent& );

public:
	/** Constructor */
	RoserrPanel( wxWindow* parent );
	///Sets panel to enabled or disabled
	void SetEnabled(bool enabled);
	///Receives roserr messages and displays them on the text control
	void WriteError(wxCommandEvent& );
	///(Callback) Tosses an event to WriteError for displaying
	void IncomingError();

	///ROS node
	ros::node *m_rosNode;
	///Message used for viewing ros error messages
	rostools::Log rosErrMsg;

	///Remembers if it is enabled or not
	bool m_Enabled;
	///Remembers if the output should use crazy colors or black
	bool m_Monochrome;
	///Remembers if the main thread is done with the message so that a new callback can be invoked
	bool m_messageIncomplete;
	///Remembers the ros subscription
	std::string m_subscription;
};

#endif // __RoserrPanel__
